server:
  http:
    addr: "0.0.0.0:8000"
    timeout: 10s
  grpc:
    addr: "0.0.0.0:8001"
    timeout: 10s

data:
  database:
    driver: "postgres"
    source: "host=127.0.0.1 user=micro-forge password=micro-forge dbname=micro-forge port=5432 sslmode=disable"
  redis:
    addr: "127.0.0.1:6379"
    password: "micro-forge_redis_pwd"
    db: 0

app:
  env: "dev"
  jwt:
    access_secret: "micro-forge_access_secret_change_me"
    refresh_secret: "micro-forge_refresh_secret_change_me"
    access_expire: 3600
    refresh_expire: 604800
  log:
    level: 0
    filename: "./logs/micro-forge.service.log"
    max_size: 20
    max_age: 30
    max_backups: 10

trace:
  endpoint: "localhost:4317"

metrics:
  enable: true

registry:
  consul:
    addr: "${REGISTRY_CONSUL_ADDR:localhost:8500}"
    scheme: "${REGISTRY_CONSUL_SCHEME:http}"
    datacenter: "${REGISTRY_CONSUL_DC:dc1}"

discovery:
  consul:
    addr: "${DISCOVERY_CONSUL_ADDR:localhost:8500}"
    scheme: "${DISCOVERY_CONSUL_SCHEME:http}"
    datacenter: "${DISCOVERY_CONSUL_DC:dc1}"
