data:
  database:
    driver: "postgres"
    source: "host=db user=krathub password=krathub dbname=krathub port=5432 sslmode=disable"
  redis:
    addr: "redis:6379"
    password: "krathub_redis_pwd"
    db: 0

registry:
  kubernetes:
    enable: true

discovery:
  kubernetes:
    enable: true
