global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: servora-service
    metrics_path: /metrics
    static_configs:
      - targets: ["servora:8000"]
        labels:
          service: servora.service
