apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

configMapGenerator:
  - name: postgres-initdb
    files:
      - init.sql
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: krathub
      app.kubernetes.io/component: api-gateway
    includeSelectors: false
