root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
entrypoint = ["./tmp/server", "-conf", "./configs/config-docker.yaml"]
include_ext = ["go", "yaml", "yml", "json"]
exclude_dir = ["tmp", "bin", ".git"]
exclude_regex = ["_test\\.go"]
delay = 300
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[misc]
clean_on_exit = true
