apiVersion: v1
kind: ConfigMap
metadata:
  name: sayhello-config
data:
  config.yaml: |
    server:
      grpc:
        addr: "0.0.0.0:8080"

    app:
      name: sayhello.service
      version: v1.0.0
      env: "prod"
      log:
        level: 0
        filename: "sayhello.log"
        max_size: 20
        max_age: 30
        max_backups: 10

    registry:
      kubernetes:
        enable: true
