app:
  env: "${ENV:prod}"
  log:
    level: "${LOG_LEVEL:-1}"
    filename: "${LOG_FILENAME:sayhello.log}"
    max_size: "${LOG_MAX_SIZE:20}"
    max_age: "${LOG_MAX_AGE:30}"
    max_backups: "${LOG_MAX_BACKUPS:10}"

registry:
  consul:
    addr: "${REGISTRY_CONSUL_ADDR:consul:8500}"
    scheme: "${REGISTRY_CONSUL_SCHEME:http}"
    datacenter: "${REGISTRY_CONSUL_DC:dc1}"

discovery:
  consul:
    addr: "${DISCOVERY_CONSUL_ADDR:consul:8500}"
    scheme: "${DISCOVERY_CONSUL_SCHEME:http}"
    datacenter: "${DISCOVERY_CONSUL_DC:dc1}"
