apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krathub

resources:
  - namespace.yaml
  - rbac.yaml
  - ../../app/krathub/service/deployment/kubernetes
  - ../../app/sayhello/service/deployment/kubernetes

labels:
  - pairs:
      app.kubernetes.io/part-of: krathub
    includeSelectors: false
