apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: micro-forge

resources:
  - namespace.yaml
  - rbac.yaml
  - ../../app/micro-forge/service/deployment/kubernetes
  - ../../app/sayhello/service/deployment/kubernetes

labels:
  - pairs:
      app.kubernetes.io/part-of: micro-forge
    includeSelectors: false
