apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: servora

resources:
  - namespace.yaml
  - rbac.yaml
  - ../../app/servora/service/deployment/kubernetes
  - ../../app/sayhello/service/deployment/kubernetes

labels:
  - pairs:
      app.kubernetes.io/part-of: servora
    includeSelectors: false
