apiVersion: v1
kind: ServiceAccount
metadata:
  name: krathub-service-account
  namespace: krathub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krathub-service-discovery
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krathub-service-discovery-binding
subjects:
  - kind: ServiceAccount
    name: krathub-service-account
    namespace: krathub
roleRef:
  kind: ClusterRole
  name: krathub-service-discovery
  apiGroup: rbac.authorization.k8s.io
