apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-forge-service-account
  namespace: micro-forge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-forge-service-discovery
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: micro-forge-service-discovery-binding
subjects:
  - kind: ServiceAccount
    name: micro-forge-service-account
    namespace: micro-forge
roleRef:
  kind: ClusterRole
  name: micro-forge-service-discovery
  apiGroup: rbac.authorization.k8s.io
