services:
  krathub:
    image: krathub:latest
    container_name: krathub
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=host=db user=krathub password=krathub dbname=krathub port=5432 sslmode=disable
      - RADDR=redis:6379
    volumes:
      - ./data/conf:/data/conf
    ports:
      - "8000:8000"
      - "8001:9000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:18.1-alpine
    container_name: krathub_db
    environment:
      POSTGRES_DB: krathub
      POSTGRES_USER: krathub
      POSTGRES_PASSWORD: krathub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U krathub -d krathub"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: krathub_redis
    command: redis-server --requirepass redisKrathub
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redisKrathub", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/redis:/data
