receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog/servora:
    include:
      - /var/log/servora/servora.service.log
    start_at: end
    include_file_path: true
    operators:
      - type: json_parser
    resource:
      service.name: servora.service
  filelog/sayhello:
    include:
      - /var/log/sayhello/sayhello.service.log
    start_at: end
    include_file_path: true
    operators:
      - type: json_parser
    resource:
      service.name: sayhello.service

processors:
  batch:
  attributes/log_hints:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: service.name,level,module,operation

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  debug:
    verbosity: basic

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, debug]
    logs:
      receivers: [filelog/servora, filelog/sayhello]
      processors: [attributes/log_hints, batch]
      exporters: [otlphttp/loki, debug]
