server:
  grpc:
    addr: "0.0.0.0:9001"
    timeout: 10s

app:
  name: "sayhello.service"
  version: "v1.0.0"
  env: "dev"
  log:
    level: 0
    filename: "./logs/sayhello.service.log"
    max_size: 20
    max_age: 30
    max_backups: 10

registry:
  consul:
    addr: "${REGISTRY_CONSUL_ADDR:localhost:8500}"
    scheme: "${REGISTRY_CONSUL_SCHEME:http}"
    datacenter: "${REGISTRY_CONSUL_DC:dc1}"

discovery:
  consul:
    addr: "${DISCOVERY_CONSUL_ADDR:localhost:8500}"
    scheme: "${DISCOVERY_CONSUL_SCHEME:http}"
    datacenter: "${DISCOVERY_CONSUL_DC:dc1}"

trace:
  endpoint: "${TRACE_ENDPOINT:localhost:4317}"

metrics:
  enable: ${METRICS_ENABLE:true}
